### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by ibrahimhalici** [mlhekinci/iOS-ToDo-VIPER#1]
Hi, when I try to build your xcodeproj file got an error of those file names below couldn't be find. Also is the path for FMDatabase-and related files, hard-coded? It doesn't search in the project folder, instead it checks for downloads.

FMDatabaseAdditions.m
FMDatabasePool.m
FMDatabaseAdditions.m

Do you know what causes this?

**Comment by mlhekinci** [comment]
Hi @ibrahimhalici 
Thank you for your interest. Sometimes Xcode versions can have problems copying files. I tried to clone the project on the error you created and observed the same errors. Then I added the files correctly again. Can you get a pull from master and try again?

**Comment by ibrahimhalici** [comment]
thanks. it worked.
